// <auto-generated />
using System;
using LaRottaO.AspNetCore.CRUDExample.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaRottaO.AspNetCore.CRUDExample.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LaRottaO.AspNetCore.CRUDExample.Models.Collaborator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EntryCreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("collaborator_table", (string)null);
                });

            modelBuilder.Entity("LaRottaO.AspNetCore.CRUDExample.Models.CollaboratorData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivitySummary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EntryCreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("HadBreakfast")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HadDinner")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HadLunch")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("OverTimeEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("OverTimeStart")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("PassportNumber");

                    b.ToTable("collaborator_data_table", (string)null);
                });

            modelBuilder.Entity("LaRottaO.AspNetCore.CRUDExample.Models.CollaboratorData", b =>
                {
                    b.HasOne("LaRottaO.AspNetCore.CRUDExample.Models.Collaborator", null)
                        .WithMany("CollaboratorDataEntries")
                        .HasForeignKey("PassportNumber")
                        .HasPrincipalKey("PassportNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LaRottaO.AspNetCore.CRUDExample.Models.Collaborator", b =>
                {
                    b.Navigation("CollaboratorDataEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
